# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  schedule:
    - cron: 0 21 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          #
          # ========================固件定制部分========================
          #
          CONFIG_TARGET_bcm27xx=y
          CONFIG_TARGET_bcm27xx_bcm2711=y
          CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y
          CONFIG_ARIA2_BITTORRENT=y
          CONFIG_ARIA2_NOXML=y
          CONFIG_ARIA2_OPENSSL=y
          CONFIG_ARIA2_WEBSOCKET=y
          CONFIG_BATMAN_ADV_BATMAN_V=y
          CONFIG_BATMAN_ADV_BLA=y
          CONFIG_BATMAN_ADV_DAT=y
          CONFIG_BATMAN_ADV_MCAST=y
          CONFIG_DOCKER_CGROUP_OPTIONS=y
          CONFIG_DOCKER_NET_MACVLAN=y
          CONFIG_DOCKER_STO_EXT4=y
          CONFIG_GNUTLS_ALPN=y
          CONFIG_GNUTLS_ANON=y
          CONFIG_GNUTLS_DTLS_SRTP=y
          CONFIG_GNUTLS_HEARTBEAT=y
          CONFIG_GNUTLS_OCSP=y
          CONFIG_GNUTLS_PSK=y
          CONFIG_KERNEL_CGROUP_DEVICE=y
          CONFIG_KERNEL_CGROUP_FREEZER=y
          CONFIG_KERNEL_CGROUP_NET_PRIO=y
          CONFIG_KERNEL_EXT4_FS_POSIX_ACL=y
          CONFIG_KERNEL_EXT4_FS_SECURITY=y
          CONFIG_KERNEL_FS_POSIX_ACL=y
          CONFIG_KERNEL_NET_CLS_CGROUP=y
          CONFIG_LIBCURL_COOKIES=y
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          CONFIG_LIBCURL_HTTP=y
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          CONFIG_LIBCURL_PROXY=y
          CONFIG_LXC_SECCOMP=y
          CONFIG_NFS_KERNEL_SERVER_V4=y
          CONFIG_NGINX_HEADERS_MORE=y
          CONFIG_NGINX_HTTP_ACCESS=y
          CONFIG_NGINX_HTTP_AUTH_BASIC=y
          CONFIG_NGINX_HTTP_AUTOINDEX=y
          CONFIG_NGINX_HTTP_BROWSER=y
          CONFIG_NGINX_HTTP_CACHE=y
          CONFIG_NGINX_HTTP_CHARSET=y
          CONFIG_NGINX_HTTP_EMPTY_GIF=y
          CONFIG_NGINX_HTTP_FASTCGI=y
          CONFIG_NGINX_HTTP_GEO=y
          CONFIG_NGINX_HTTP_GZIP=y
          CONFIG_NGINX_HTTP_LIMIT_CONN=y
          CONFIG_NGINX_HTTP_LIMIT_REQ=y
          CONFIG_NGINX_HTTP_MAP=y
          CONFIG_NGINX_HTTP_MEMCACHED=y
          CONFIG_NGINX_HTTP_PROXY=y
          CONFIG_NGINX_HTTP_REFERER=y
          CONFIG_NGINX_HTTP_REWRITE=y
          CONFIG_NGINX_HTTP_SCGI=y
          CONFIG_NGINX_HTTP_SPLIT_CLIENTS=y
          CONFIG_NGINX_HTTP_SSI=y
          CONFIG_NGINX_HTTP_UPSTREAM_HASH=y
          CONFIG_NGINX_HTTP_UPSTREAM_IP_HASH=y
          CONFIG_NGINX_HTTP_UPSTREAM_KEEPALIVE=y
          CONFIG_NGINX_HTTP_UPSTREAM_LEAST_CONN=y
          CONFIG_NGINX_HTTP_USERID=y
          CONFIG_NGINX_HTTP_UWSGI=y
          CONFIG_NGINX_HTTP_V2=y
          CONFIG_NGINX_NAXSI=y
          CONFIG_NGINX_PCRE=y
          CONFIG_NGINX_UBUS=y
          CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
          CONFIG_PACKAGE_adb=y
          CONFIG_PACKAGE_adb-enablemodem=y
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_ariang=y
          CONFIG_PACKAGE_batctl-default=y
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_ca-certificates=y
          CONFIG_PACKAGE_cgroupfs-mount=y
          CONFIG_PACKAGE_chat=y
          CONFIG_PACKAGE_comgt=y
          CONFIG_PACKAGE_comgt-directip=y
          CONFIG_PACKAGE_comgt-ncm=y
          CONFIG_PACKAGE_containerd=y
          CONFIG_PACKAGE_dawn=y
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_dockerd=y
          CONFIG_PACKAGE_edgeport-firmware=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_flock=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_frps=y
          CONFIG_PACKAGE_fuse-utils=y
          CONFIG_PACKAGE_getopt=y
          CONFIG_PACKAGE_hd-idle=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_kmod-batman-adv=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-cts=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-dax=y
          CONFIG_PACKAGE_kmod-dm=y
          CONFIG_PACKAGE_kmod-dnsresolver=y
          CONFIG_PACKAGE_kmod-dummy=y
          CONFIG_PACKAGE_kmod-fs-btrfs=y
          CONFIG_PACKAGE_kmod-fs-exportfs=y
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y
          CONFIG_PACKAGE_kmod-fs-nfs-ssc=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-nfsd=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-ntfs3-oot=y
          CONFIG_PACKAGE_kmod-fs-reiserfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          CONFIG_PACKAGE_kmod-fuse=y
          CONFIG_PACKAGE_kmod-hwmon-core=y
          CONFIG_PACKAGE_kmod-hwmon-raspberrypi=y
          CONFIG_PACKAGE_kmod-hwmon-rpi-poe-fan=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-ikconfig=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-keys-encrypted=y
          CONFIG_PACKAGE_kmod-keys-trusted=y
          CONFIG_PACKAGE_kmod-lib-crc16=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-raid6=y
          CONFIG_PACKAGE_kmod-lib-xor=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-lib-zstd=y
          CONFIG_PACKAGE_kmod-libphy=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-nf-ipvs=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-nft-bridge=y
          CONFIG_PACKAGE_kmod-nft-core=y
          CONFIG_PACKAGE_kmod-nft-netdev=y
          CONFIG_PACKAGE_kmod-oid-registry=y
          CONFIG_PACKAGE_kmod-random-core=y
          CONFIG_PACKAGE_kmod-sched-connmark=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-tpm=y
          CONFIG_PACKAGE_kmod-usb-acm=y
          CONFIG_PACKAGE_kmod-usb-ehci=y
          CONFIG_PACKAGE_kmod-usb-gadget=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-aqc111=y
          CONFIG_PACKAGE_kmod-usb-net-asix=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-eem=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-subset=y
          CONFIG_PACKAGE_kmod-usb-net-dm9601-ether=y
          CONFIG_PACKAGE_kmod-usb-net-hso=y
          CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm=y
          CONFIG_PACKAGE_kmod-usb-net-ipheth=y
          CONFIG_PACKAGE_kmod-usb-net-kalmia=y
          CONFIG_PACKAGE_kmod-usb-net-kaweth=y
          CONFIG_PACKAGE_kmod-usb-net-mcs7830=y
          CONFIG_PACKAGE_kmod-usb-net-pegasus=y
          CONFIG_PACKAGE_kmod-usb-net-pl=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8150=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_kmod-usb-net-sierrawireless=y
          CONFIG_PACKAGE_kmod-usb-net-smsc75xx=y
          CONFIG_PACKAGE_kmod-usb-net-smsc95xx=y
          CONFIG_PACKAGE_kmod-usb-net-sr9700=y
          CONFIG_PACKAGE_kmod-usb-net2280=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb-printer=y
          CONFIG_PACKAGE_kmod-usb-serial=y
          CONFIG_PACKAGE_kmod-usb-serial-ark3116=y
          CONFIG_PACKAGE_kmod-usb-serial-belkin=y
          CONFIG_PACKAGE_kmod-usb-serial-ch341=y
          CONFIG_PACKAGE_kmod-usb-serial-cp210x=y
          CONFIG_PACKAGE_kmod-usb-serial-cypress-m8=y
          CONFIG_PACKAGE_kmod-usb-serial-dmx_usb_module=y
          CONFIG_PACKAGE_kmod-usb-serial-edgeport=y
          CONFIG_PACKAGE_kmod-usb-serial-ftdi=y
          CONFIG_PACKAGE_kmod-usb-serial-garmin=y
          CONFIG_PACKAGE_kmod-usb-serial-ipw=y
          CONFIG_PACKAGE_kmod-usb-serial-keyspan=y
          CONFIG_PACKAGE_kmod-usb-serial-mct=y
          CONFIG_PACKAGE_kmod-usb-serial-mos7720=y
          CONFIG_PACKAGE_kmod-usb-serial-mos7840=y
          CONFIG_PACKAGE_kmod-usb-serial-option=y
          CONFIG_PACKAGE_kmod-usb-serial-oti6858=y
          CONFIG_PACKAGE_kmod-usb-serial-pl2303=y
          CONFIG_PACKAGE_kmod-usb-serial-qualcomm=y
          CONFIG_PACKAGE_kmod-usb-serial-sierrawireless=y
          CONFIG_PACKAGE_kmod-usb-serial-simple=y
          CONFIG_PACKAGE_kmod-usb-serial-ti-usb=y
          CONFIG_PACKAGE_kmod-usb-serial-visor=y
          CONFIG_PACKAGE_kmod-usb-serial-wwan=y
          CONFIG_PACKAGE_kmod-usb-serial-xr_usb_serial_common=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_kmod-usb-storage-uas=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-usb-wdm=y
          CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_kmod-veth=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libdevmapper=y
          CONFIG_PACKAGE_libfdisk=y
          CONFIG_PACKAGE_libfreetype=y
          CONFIG_PACKAGE_libfuse=y
          CONFIG_PACKAGE_libgcrypt=y
          CONFIG_PACKAGE_libgd-full=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_libgpg-error=y
          CONFIG_PACKAGE_libjpeg-turbo=y
          CONFIG_PACKAGE_libkeyutils=y
          CONFIG_PACKAGE_liblxc=y
          CONFIG_PACKAGE_liblzo=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnetwork=y
          CONFIG_PACKAGE_libnftnl=y
          CONFIG_PACKAGE_libpcre2=y
          CONFIG_PACKAGE_libpng=y
          CONFIG_PACKAGE_libseccomp=y
          CONFIG_PACKAGE_libsqlite3=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libtiff=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_libusb-1.0=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libwebp=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libwrap=y
          CONFIG_PACKAGE_libxml2=y
          CONFIG_PACKAGE_libzip-gnutls=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-docker=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-easymesh=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-frps=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-kodexplorer=y
          CONFIG_PACKAGE_luci-app-lxc=y
          CONFIG_PACKAGE_luci-app-nfs=y
          CONFIG_PACKAGE_luci-app-nft-qos=y
          CONFIG_PACKAGE_luci-app-pppoe-relay=y
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-rclone=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-docker-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-easymesh-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-frps-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-kodexplorer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-nft-qos-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-pppoe-relay-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-rclone-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-webadmin-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-lib-docker=y
          CONFIG_PACKAGE_luci-nginx=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-ssl-nginx=y
          CONFIG_PACKAGE_luci-ssl-openssl=y
          CONFIG_PACKAGE_lxc=y
          CONFIG_PACKAGE_lxc-attach=y
          CONFIG_PACKAGE_lxc-common=y
          CONFIG_PACKAGE_lxc-configs=y
          CONFIG_PACKAGE_lxc-console=y
          CONFIG_PACKAGE_lxc-create=y
          CONFIG_PACKAGE_lxc-hooks=y
          CONFIG_PACKAGE_lxc-templates=y
          CONFIG_PACKAGE_mount-utils=y
          CONFIG_PACKAGE_nfs-kernel-server=y
          CONFIG_PACKAGE_nfs-kernel-server-utils=y
          CONFIG_PACKAGE_nfs-utils=y
          CONFIG_PACKAGE_nfs-utils-libs=y
          CONFIG_PACKAGE_nft-qos=y
          CONFIG_PACKAGE_nftables-nojson=y
          CONFIG_PACKAGE_nginx=y
          CONFIG_PACKAGE_nginx-mod-luci=y
          CONFIG_PACKAGE_nginx-mod-luci-ssl=y
          CONFIG_PACKAGE_nginx-ssl=y
          CONFIG_PACKAGE_nginx-ssl-util=y
          CONFIG_PACKAGE_nginx-util=y
          CONFIG_PACKAGE_oniguruma=y
          CONFIG_PACKAGE_php8=y
          CONFIG_PACKAGE_php8-cgi=y
          CONFIG_PACKAGE_php8-fastcgi=y
          CONFIG_PACKAGE_php8-fpm=y
          CONFIG_PACKAGE_php8-mod-curl=y
          CONFIG_PACKAGE_php8-mod-dom=y
          CONFIG_PACKAGE_php8-mod-gd=y
          CONFIG_PACKAGE_php8-mod-iconv=y
          CONFIG_PACKAGE_php8-mod-mbstring=y
          CONFIG_PACKAGE_php8-mod-mysqlnd=y
          CONFIG_PACKAGE_php8-mod-opcache=y
          CONFIG_PACKAGE_php8-mod-pdo=y
          CONFIG_PACKAGE_php8-mod-pdo-mysql=y
          CONFIG_PACKAGE_php8-mod-pdo-sqlite=y
          CONFIG_PACKAGE_php8-mod-session=y
          CONFIG_PACKAGE_php8-mod-sqlite3=y
          CONFIG_PACKAGE_php8-mod-xml=y
          CONFIG_PACKAGE_php8-mod-xmlreader=y
          CONFIG_PACKAGE_php8-mod-xmlwriter=y
          CONFIG_PACKAGE_php8-mod-zip=y
          CONFIG_PACKAGE_qos-scripts=y
          CONFIG_PACKAGE_r8152-firmware=y
          CONFIG_PACKAGE_rclone=y
          CONFIG_PACKAGE_rclone-config=y
          CONFIG_PACKAGE_rclone-ng=y
          CONFIG_PACKAGE_rclone-webui-react=y
          CONFIG_PACKAGE_rp-pppoe-common=y
          CONFIG_PACKAGE_rp-pppoe-relay=y
          CONFIG_PACKAGE_rpcbind=y
          CONFIG_PACKAGE_rpcd-mod-lxc=y
          CONFIG_PACKAGE_runc=y
          CONFIG_PACKAGE_samba36-server=y
          CONFIG_PACKAGE_tc-mod-iptables=y
          CONFIG_PACKAGE_tc-tiny=y
          CONFIG_PACKAGE_tini=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_umbim=y
          CONFIG_PACKAGE_umdns=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_uqmi=y
          CONFIG_PACKAGE_usb-modeswitch=y
          CONFIG_PACKAGE_uwsgi=y
          CONFIG_PACKAGE_uwsgi-cgi-plugin=y
          CONFIG_PACKAGE_uwsgi-luci-support=y
          CONFIG_PACKAGE_uwsgi-syslog-plugin=y
          CONFIG_PACKAGE_wpa-supplicant-mesh-openssl=m
          CONFIG_PACKAGE_wpad-basic-wolfssl=m
          CONFIG_PACKAGE_wpad-mesh-openssl=y
          CONFIG_PACKAGE_wpad-openssl=y
          CONFIG_PACKAGE_wwan=y
          CONFIG_PACKAGE_zoneinfo-asia=y
          CONFIG_PACKAGE_zoneinfo-core=y
          CONFIG_PHP8_LIBXML=y
          CONFIG_PHP8_SYSTEMTZDATA=y
          CONFIG_RPCBIND_LIBWRAP=y
          CONFIG_RPCBIND_RMTCALLS=y
          CONFIG_SQLITE3_DYNAMIC_EXTENSIONS=y
          CONFIG_SQLITE3_FTS3=y
          CONFIG_SQLITE3_FTS4=y
          CONFIG_SQLITE3_FTS5=y
          CONFIG_SQLITE3_JSON1=y
          CONFIG_SQLITE3_RTREE=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          CONFIG_PACKAGE_libwolfssl=y
          #
          # ========================固件定制部分结束========================
          #
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
  

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
